version: "3.9"
services:
  db:
    image: mysql:8
    container_name: habitapp-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: habitsdb
      MYSQL_USER: habituser
      MYSQL_PASSWORD: habitpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
